# references:
# * http://www.objc.io/issue-6/travis-ci.html

osx_image: xcode11.5
language: swift

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Rikimaru.xcworkspace -scheme Rikimaru -sdk iphonesimulator14.0.1 ONLY_ACTIVE_ARCH=NO | xcpretty
